[Connection]
; Define server behavior.
; 0. Server + Client: Runs the server and starts the game client.
; 1. Server: Runs the server without client execution.
; 2. Client: Disables server emulation and starts the game client.
ServerMode=0
; Define server host.
; Localhost: Connect to a local server. Ideal for single-player.
; Private: Connect to a server over a LAN connection. Ideal for local play.
; Public: Connect to a server over a WAN connection. Ideal for online play.
ServerHost=127.0.0.1

[Options]
; Allow unregistered users to be registered at the login screen.
Register=0
; Allow users to have mutiple scores (and replays) in the global rankings.
; Don't change once the database has already been created.
MultiScores=0
; Define notice message text.
; 0. No message text.
; 1. Custom message text.
NoticeMode=1
NoticeText=Jewelry Master - Server Emulator by Hipnosis.